Implement before parameter.
Metatavu/time-bank-ui pull request #108
Opened 2023-02-14 12:23 UTC by VeikkoVilpponen

Added before parameter with value of yesterday to make sure today's time entries are not included in statistics.

2023-02-14 12:25 UTC, Kaitsuus reviewed
Looks good to me

2023-02-14 14:04 UTC, Jdallos requested changes

2023-02-14 14:04 UTC, Jdallos commented on src/components/drawer-content/drawer-content.tsx
> +  const yesterday = (d => new Date(d.setDate(d.getDate() - 1)))(new Date());
Can this be simplified? Lets discuss

2023-02-15 09:19 UTC, Kaitsuus reviewed
Awesome

2023-02-15 10:56 UTC, Jdallos approved these changes

2023-02-15 10:56 UTC, merged