Issue #110 employy vacation forms UI
Metatavu/time-bank-ui pull request #115
Opened 2023-04-13 06:50 UTC by LaGyn

My vacations, employee vacation requests

2023-04-17 07:05 UTC, Jdallos requested changes
Have fun! Happy to discuss anything that is not clear.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +/* eslint-disable */
Is this needed?

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +import React, { ChangeEvent, useState } from "react";
Currently the general practice is to avoid importing the React namespace and destructuring imports directly. E.g. rather than using React.FC (line 47) you can import FC directly as is done already for useState.
If you have time feel free to remove the React throughout the project but this is not a priority right now, just keep it in mind for the future.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const [ dateVacationFormat, setDateVacationFormat ] = React.useState<string | undefined>("yyyy.MM.dd");
Does this need to be typed as string or undefined as you initialize the state with a string.
If not then there is no need to even set a type here as react can infer it.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const [ datePickerViewVacation, setDatePickerViewVacation ] = React.useState<CalendarPickerView>("day");
As mentioned earlier 
```suggestion
  const [ datePickerViewVacation, setDatePickerViewVacation ] = useState<CalendarPickerView>("day");
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const [ selectedVacationEndDate, setSelectedVacationEndDate ] = useState<any>(new Date())
Can these by typed as Date? Avoid the use of any where possible

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const [ selectedVacationEndDate, setSelectedVacationEndDate ] = useState<any>(new Date())
```suggestion
  const [ selectedVacationStartDate, setSelectedVacationStartDate ] = useState<any>(new Date());
  const [ selectedVacationEndDate, setSelectedVacationEndDate ] = useState<any>(new Date());
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    console.log(date);
Remove console.logs when committing code/ before a review unless there is a reason for it to be left in

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +
No need for a blank line here
```suggestion    
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +
```suggestion
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    console.log(date);
Remove as above

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  * Test new vacation calculations
Missing @params in the JSDoc comment

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  function getVacationDays(startDate: Date, endDate: Date, holidays: Date[]): number{
```suggestion
  const  getVacationDays = (startDate: Date, endDate: Date, holidays: Date[]): number => {
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  function getVacationDays(startDate: Date, endDate: Date, holidays: Date[]): number{
Generally use arrow function syntax

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    const totalDays = Math.round((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
```suggestion
    const totalDays = Math.round((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  }
Lots of missing semi-colons ; here

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +        if (currentDate.getDay() != 0 && !holidays.some(holiday => holiday.getTime() === currentDate.getTime())) {
There is quite a lot of logic going on in this conditional, could the logic be put in its own function which returned a boolean, the boolean can then be stored in an appropriately named variable and then passed into the condition.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    let currentDate = new Date(startDate)
```suggestion
    let currentDate = new Date(startDate);
    
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const startDate = new Date(selectedVacationStartDate)
```suggestion
  const startDate = new Date(selectedVacationStartDate);
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const endDate = new Date(selectedVacationEndDate)
```suggestion
  const endDate = new Date(selectedVacationEndDate);
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  ]
```suggestion
  ];
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const holidays = [
Can these dates be set so that they will work for multiple years?

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +   * Renders and calculates days spend for vacation
If I understand correctly spent is clearer than spend here.
```suggestion
   * Renders and calculates days spent for vacation
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const renderVacationDaysSpend = () => {
You could update the function name as mentioned above, remember to also update function calls.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    let days = 0
Missing semi-colons; This rule can be configured within the linter. At the moment this project isn't consistent, some places uses them and in others it doesn't, so lets try to use semi-colons in all appropriate places

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +        {(`Amount of vacation days spend ${days}`)}
Similar consistency issue here with curly brackets as with the semi-colons. In some places there are spaces within the curley brackets e.g { variablename } and in other places not e.g. {variableName}. Lets me consistent and go for with spaces. Agign this can be configured in the linter, maybe check your linter is working?

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  * Handle vacation comment box content
Missing @param comment

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +   * Handle vacation type
Missing @param comment

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +      <InputLabel>Vacation type</InputLabel>
Use localization as in other places for rendering strings e.g. { string.groupName.stringName }

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +        label="Type"
Use localization as in other places for rendering strings e.g. { string.groupName.stringName }

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +        <MenuItem value={"Surplus balance"}>Surplus balance</MenuItem>
Use localization as in other places for rendering strings e.g. { string.groupName.stringName }

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +        <MenuItem value={"Surplus balance"}>Surplus balance</MenuItem>
Try to do this throughout the changes you have made, I won't comment about this any more in order to keep  the review 'clean'

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const handleVacationApplyButton = () => {
I suspect this functionality is not yet full implemented, hence the console.log?
If this is the case you can make functions not yet finished with a TODO: comment

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    */
```suggestion
  /**
   * Renders vacation apply button
   */
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +        { (`APPLY`) }
Is there a reason for the parenthesis and the back ticks?

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    */
JSDoc comment indentation is off in a few places, this is how it should be, try to fix when you notice it.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  const handleVacationStartDateChange = (date: unknown) => {
Can this by types as Date?

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    date && setSelectedVacationStartDate(date);
Perhaps this conditional is only needed because of the unknown type and so could be removed when the type is updated.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    date && setSelectedVacationEndDate(date);
Same as above

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +   *
```suggestion
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +      >
Check indentation

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    }
```suggestion
    }
    
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +    <Accordion className={classes.vacationDaysAccordion}>
Check indentation here, the content of the return should be indented from the return

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +            { `Apply for vacation` }
This should be localized as mentioned previously. Also If you are not using template literals to render a variable then you do not need to use back ticks.

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +                      />
Fix indentation

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +                        onStartWeekChange={function (): void {
No need to throw an error if the function is not yet implemented, perhaps this could be disabled?
Although if this is just flashing up a message in an error dialog and its only temporary perhaps its fine...

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +  }
```suggestion
  };
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/editor-content/editor-content.tsx
> +   *
Missing description

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/date-range-picker/test-date-range-picker.tsx
> +/* eslint-disable */
Is this needed? If so why?

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/date-range-picker/test-date-range-picker.tsx
> +
```suggestion
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/date-range-picker/test-date-range-picker.tsx
> +  selectedFilteredStartDate: unknown;
Try to change all unknown types

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/date-range-picker/test-date-range-picker.tsx
> +const DateFilterPicker: React.FC<Props> = ({
As mentioned for previous files destructure imports rather than use the React.FC

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/date-range-picker/test-date-range-picker.tsx
> +   * Initialize the date data
Is this comment actually describing what is happening here?

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +/* eslint-disable */
Needed?

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +const createData = (
Is there a reason this createData is typed like this rather than as an interface for Props as in other components e.g. myVacationComponent.tsx

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +const StyledTableCell = styled(TableCell)(({ theme }) => ({
JSDocs

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> + *
```suggestion
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +const ExpandableRow = (props: { request: ReturnType<typeof createData> }) => {
See above for updating this to by types as props, which in this case it looks like only need contain the request (which will be the createData type)

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +                    <TableCell>Human resources manager:</TableCell>
Use localization

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +
```suggestion
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> + *
```suggestion
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  const [ selectedVacationEndDate, setSelectedVacationEndDate ] = useState<any>(new Date())
Can this be typed as Date rather than any?

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +          <em>None</em>
Localization

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +     * Method to handle vacation starting date change
JSDoc indentation

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  const handleVacationStartDateChange = (date: unknown) => {
Change type to date and then can remove the conditional date &&

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  const handleVacationEndDateChange = (date: unknown) => {
Change type to date and then can remove the conditional date &&

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  const renderVacationType = () => (
I feel like I have seen this select component somewhere else. Could this be exported and used as its own component? I could be mistaken...

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationComponent.tsx
> +  onEndDateChange: (value: any) => void;
Can this be typed more specifically than any?

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationComponent.tsx
> +  }
Check indentation

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +import DateFilterPicker from '../date-range-picker/test-date-range-picker';
use double quotes

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> + *
```suggestion
```

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  const [selectedVacationEndDate, setSelectedVacationEndDate] = useState<any>(new Date())
Can this be types as Date rather than any?

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  const renderVacationType = () => (
Again this component looks similar to one previously mentioned, could this be exported from a generic file of some kind?

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  const handleVacationApplyButton = () => {
Im seeing a lot of repetition in this file, it looks quite similar to the a lot of content in the editor-content.tsx. Can you confirm this duplication is necessary. We can discuss together if needed

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationsDatePicker.tsx
> +  onEndDateChange: (value: any) => void;
Avoid any type if possible

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationMockData.json
> +[
I'm not seeing any tests, is this just something you are using locally, in which case does it need to be committed? Perhaps you can either delete it when you are finished, or not commit it, or add it to the .gitignore but I don't see any reason for this to be here. Let me know if I'm mistaken

2023-04-17 07:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/testVacationMockData.json
> +[
I'm not seeing any tests, is this just something you are using locally, in which case does it need to be committed? Perhaps you can either delete it when you are finished, or not commit it, or add it to the .gitignore but I don't see any reason for this to be here. Let me know if I'm mistaken

2023-04-19 13:05 UTC, Jdallos approved these changes
Some comments and suggestions then approved

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +/* eslint-disable @typescript-eslint/no-shadow */
Is this needed?

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  // eslint-disable-next-line no-restricted-globals
Is this needed?

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +const ExpandableRow: React.FC<Request> = ({ request }) => {
Destructure from React as import

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> + * Expandable row
Missing @param docs

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  const [ dateFormat ] = useState<string>("yyyy.MM.dd");
You should be able to remove the generic typing <string> as the type should be inferred in this case.

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  const [ selectedVacationEndDate, setSelectedVacationEndDate ] = useState<Date>(new Date());
You should be able to remove the generic typing <Date> as the type should be inferred in this case.

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +   * Handle employee change
Missing @ param docs

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +  const renderVacationType = () => (
Perhaps you can create a task in trello detailing this file/ functions and the refactoring. Then this conversation can be resolved

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +        m: 1, minWidth: 165, marginBottom: 4
```suggestion
        m: 1,
        minWidth: 165,
        marginBottom: 4
```

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +        m: 1, minWidth: 165, marginBottom: 4
Once there are three 'arguments' in a line, each one can go on a new line for code clarity

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +   * Handle employee change
issing @param doc

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +        m: 1, minWidth: 165, marginBottom: 4
```suggestion
        m: 1,
        minWidth: 165,
        marginBottom: 4
```

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +        m: 1, minWidth: 165, marginBottom: 4
Once there are three 'arguments' in a line, each one can go on a new line for code clarity

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +        m: 1, minWidth: 165, marginBottom: 4
is there a reason m is used here rather than margin, perhaps margin is better to use for clarity

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +          float: "right", paddingRight: "15px", marginBottom: "10px"
```suggestion
          float: "right",
          paddingRight: "15px", 
          marginBottom: "10px"
```

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +          float: "right", paddingRight: "15px", marginBottom: "10px"
Once there are three 'arguments' in a line, each one can go on a new line for code clarity

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +              onStartWeekChange={function (): void {
Can this be done as an inline arrow functions e.g.:

() => throw new Error("Function not implemented.")

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +              onStartWeekChange={function (): void {
If this works then you should be able to remove the eslint disable comments.

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +              onEndDateChange={handleVacationEndDateChange}
```suggestion
              scope={ FilterScopes.DATE }
              dateFormat={ dateFormat }
              selectedStartDate={ selectedVacationStartDate }
              selectedEndDate={ selectedVacationEndDate }
              datePickerView={ datePickerView }
              onStartDateChange={ handleVacationStartDateChange }
              onEndDateChange={ handleVacationEndDateChange }
```

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/employeeVacationRequests.tsx
> +              onEndDateChange={handleVacationEndDateChange}
Still a few inconsistencies in curly bracket spacings

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +import React, { useState } from "react";
The React import should be removed and all React.import uses should be destructured here as is being done for useState

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +interface Request {
Missing JSDocs

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  const [selectedVacationEndDate, setSelectedVacationEndDate] = useState<Date>(new Date());
Type should be automatically inferred for these

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  const renderVacationType = () => (
Once the task for refactoring is created in Trello this can be resolved

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +    setNewVacationType(contentValue as string);
I don't think this type casting is needed here, contentValue is already a string so you can remove the 'as string'

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +        m: 1, minWidth: 165, marginBottom: 4
```suggestion
        m: 1, 
        minWidth: 165, 
        marginBottom: 4
```

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  * Handle vacation comment box content
Missing @param doc

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +      onChange={handleVacationCommentContent}
```suggestion
      value={ newTextContent }
      onChange={ handleVacationCommentContent }
```

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  const handleVacationApplyButton = () => {
Once the task for refactoring is created in Trello this can be resolved

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +  /**
Indentation

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +      console.log(`this is START DATE ${selectedVacationStartDate} and this is END DATE${selectedVacationEndDate} and this is TEXT CONTENT ${textContent}. Vacation type ${vacationType}`)
Is this console log needed or is this function to be implemented in the future, in which case a comment about not yet implemented would be a good thing

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +                    {" "}
What is this doing, could the desired result be achieved with styling?

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +                            // onClick={ handleStartDateOnlyClick }
This could be removed or commented as  TODO: not yet implemented

2023-04-19 13:05 UTC, Jdallos commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +                              dateFormat={dateFormat}
Curly bracket spacing inconsistency

2023-04-20 09:25 UTC, LaGyn commented on src/components/generics/vacation-test-forms/myVacationRequests.tsx
> +import React, { useState } from "react";
Resolved this by adding:
"react/react-in-jsx-scope": "off",
"react/jsx-uses-react": "off",
"react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
to .eslintrc.json. Hope it's fine.

2023-04-21 05:23 UTC, closed without merging